name: "Build and Publish Package on Gemfury"

on:
  release:
    types: [published, edited]

jobs:
  publish-on-release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build Package
        run: python setup.py sdist

      - name: Prepare build artifact
        id: prep
        run: |
          BUILD_FILE=build.$(date +%Y-%m-%d-%H-%M).tgz
          echo ::set-output name=build_name::${BUILD_FILE}
          echo ::set-output name=build_path::$(ls -t dist/*gz | head -1)

      - name: Save build as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.prep.outputs.build_name }}
          path: ${{ steps.prep.outputs.build_path }}
          retention-days: 5

      - name: Publish Package
        run: curl -F package=@${{ steps.prep.outputs.build_path }} https://${{ secrets.GEMFURY_PUSH_TOKEN }}@push.fury.io/ssaunier/
