name: "Run Test"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -e .

      - name: Install package and test
        run: |
          make pytest
